//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TejidosPaupiSoft.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Compras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compras()
        {
            this.InsumosXCompra = new HashSet<InsumosXCompra>();
        }
    
        public int Id { get; set; }
        public int Numero { get; set; }
       
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime Fecha { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Subtotal { get; set; }
        public Nullable<int> Descuentos { get; set; }
        public Nullable<int> Total { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsumosXCompra> InsumosXCompra { get; set; }
    }
}
